Added guard

diff --git a/.chezmoiscripts/run_after_02-install-homebrew b/.chezmoiscripts/run_after_02-install-homebrew
--- a/.chezmoiscripts/run_after_02-install-homebrew
+++ b/.chezmoiscripts/run_after_02-install-homebrew
@@ -2,6 +2,11 @@
 
 set -eufo pipefail
 
+if ! command -v curl &> /dev/null; then
+    echo "Unable to find the 'curl' command. Aborting."
+    exit 1
+fi
+
 if ! command -v brew &> /dev/null; then
     url="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
     if bash -c "$(curl -fsSL $url)"; then
